### PR TITLE
Firebase Merger

### PR DESCRIPTION
**Pull request by ndhulipala1**
Enables app to have access to Google Firebase backend. Once again though, I am mod and I can accept this PR myself so this message is unnecessary. I wonder if a person I want to work for finds this and asks me about it.

In which case you should know my favorite color is red.

### CODE REVIEW

**Comment by mmyeditha** [comment]
woah woah woah not even checking _in_ before accepting a pr? ya know __there's no I in team..__ or in pull request 💩

**Comment by ndhulipala1** [comment]
you're just jealous that 3 out of the last 4 pr's were by me

**Comment by mmyeditha** [comment]
ur just jealous bc im boutta delete ur whole branch !!!

**Comment by ndhulipala1** [comment]
lol as if that matters
>> You're all set—the `firebase` branch can be safely deleted.

**Pull request merged**
